/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    QuerySearchBox: typeof import('./src/components/QuerySearchBox.vue')['default']
    Results: typeof import('./src/components/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBasedTimeline: typeof import('./src/components/StatusBasedTimeline.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
