/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIBulletin: typeof import('./src/components/AIBulletin.vue')['default']
    ChatBubble: typeof import('./src/components/ChatBubble.vue')['default']
    ChatContainer: typeof import('./src/components/ChatContainer.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    QuerySearchBox: typeof import('./src/components/QuerySearchBox.vue')['default']
    Results: typeof import('./src/components/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StatusBasedTimeline: typeof import('./src/components/StatusBasedTimeline.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UTimeline: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue')['default']
  }
}
